model_path: "./mast3r/checkpoints/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth"
ransac:
  use_ransac: False
  max_iters: 100
  inlier_ratio: 0.5
  error_threshold: 0.01
  min_samples: 2
ba:
  max_iter: 10
  tolerance: 0.001
  huber_delta: 1.0 # Huber loss threshold
  damping_factor: 0.001 # Regularization parameter in LM
