model_path: "./mast3r/checkpoints/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth"
ransac:
  use_ransac: False
  max_iters: 100
  inlier_ratio: 0.5
  error_threshold: 0.01
  min_samples: 2
ba_max_iter: 10
ba_tolerance: 0.001
